### ISSUE TITLE
authentication for endnbote not working correctly

### ISSUE THREAD

**Issue by dallison1** [unl-libraries/ezproxy#14]
It looks like this is what most sites with help guides say to put in the authentication part of endnotes: http://libproxy.unl.edu/login  I've also tried adding the url= part as well but links that are pulled into endnotes also send me to the main page (database listing) on Ezproxy server.  I can show you what this looks like.  I'm wondering if there is something missing from the ezproxy configuration?

**Comment by dallison1** [comment]
I'm able to bypass the database listing now but Endnote isn't adding the proxy information like it should.

**Comment by srickel1** [comment]
I'm not following this ticket.  Can you back up a bit, and explain what you are trying to do, and how do I duplicate the error?

**Comment by dallison1** [comment]
You need a copy of endnote, which is a reference manager.  Hold off on working on this until I talk with Joan K. to verify what it is supposed to be doing.  I’m not very familiar with the product.  It doesn’t  support WAM.

DeeAnn

**Comment by srickel1** [comment]
Ok - I hazarded a guess and made a change based on some information I found in the EZproxy forum.

So let me know if that made a difference

**Comment by dallison1** [comment]
Seems to be working better.  Here is one issue I found:
searched ASP in Endnote:  got this url http://library.unl.edu:4550/resserv?sid=ISI:WoS&aufirst=Cristina%20Isabel%20Oliveira&aulast=Jacome&issn=09638288&atitle=Burden%20of%20treatment%20in%20the%20light%20of%20the%20international%20classification%20of%20functioning,%20disability%20and%20health:%20a%20%22best%20fit%22%20framework%20synthesis&title=Disability%20%26%20Rehabilitation&volume=39&issue=13&date=2017&spage=9p  
Clicked on the link and got : security error - when I clicked through I got:
Can’t reach this page

•Make sure the web address http://libproxy.unl.edu is correct
•Search for this site on Bing
•Refresh the page
More information  More information   
There was a temporary DNS error. Try refreshing the page.
Error Code: INET_E_RESOURCE_NOT_FOUND

**I refreshed the page and got the same error.  Do you think is has to do with moving the server?**

**Comment by dallison1** [comment]
Hold off - my computer still doesn't see the new IP so that may the problem.

**Comment by dallison1** [comment]
I think I found a configuration issue the authenticate box of endnote is asking for a URL.  When I put in https://login.libproxy.unl.edu/login it goes to a menu html page with the database listing.  It does the same thing for: https://login.libproxy.unl.edu/login?url=   It should take me to a login box.  I can should you in my office.  Documentation from endnote suggests  https://login.libproxy.unl.edu/login  should be correct and it looks like that is confirmed by other libraries.  Does this make sense? also tried: http://login.libproxy.unl.edu/login?url=http://library.unl.edu/patroninfo   this generally takes you to the login page - this also works: https://encore.unl.edu/iii/cas/login?  maybe I have the wrong syntax for exproxy.

**Comment by srickel1** [comment]
I don't think this is a configuration problem with EZproxy.  That is the behavior if you go directly to libproxy.unl.edu without providing a url to be proxied to.  If it worked in wam, then if you take off that rewrite and use that url after "url=" then it should work.

**Comment by srickel1** [comment]
Also, I do not proxy the library patron login page. EZproxy has it's own authentication

**Comment by srickel1** [comment]
I read through all the url's you listed, and what you should be always be using for our EZproxy is:

http://libproxy.unl.edu/login?url=

Then EZproxy can redirect properly, whether the site is http or https, etc...  There was an issue after it came back up where I had tried to add some EndNote stanza information to fix whatever the unknown issue was - and it screwed up the secure rewrites.    This has been corrected.

**Comment by srickel1** [comment]
Ok - so I got full text to work with https://login.libproxy.unl.edu/ as the URL, but this was on campus.  @mlitwa can you try that off campus?  Once you get it installed, try an online search in Academic search premier or Web of Science, one you get a result, you can right click it to "Find Full Text".  

A lot of the ones on the list that were sent as problems do not seem to have pdf full texts, so this is confusing.

**Comment by srickel1** [comment]
After sitting down with Leslie and using the desktop version of Endnote, it was determined that the proxy url was working as expected.  The confusion arises from the page users are redirected to after logging in.  Since Endnote isn't sending the users to a proxied url with EZproxy, just using it to authenticate, the users are seeing in the authentication popup, the eresources page on the libraries site.  That site has a javascript error that is not handled in Endnote, so it looks like an error.  Users need only dismiss the error, and click on the "continue" box once they have logged in.  Then everything should work properly.
