### ISSUE TITLE
SAGE Journals encldoing issue

### ISSUE THREAD

**Issue by dallison1** [unl-libraries/ezproxy#15]
Sage journals won't resolve DOI because of encoding issue:
http://129.93.16.3:4550/resserv?url_ver=Z39.88-2004&url_ctx_fmt=info:ofi/fmt:kev:mtx:ctx&rft_val_fmt=info:ofi/fmt:kev:mtx:journal&rft.atitle=Quantifying%20the%20Cost%20of%20Disability%20Transitions%20in%20Medicare&rft.aufirst=Mingliang&rft.aulast=Dai&rft.date=2017&rft.eissn=1552-6887&rft.epage=804&rft.genre=article&rft.issn=0898-2643&rft.issue=5&rft.jtitle=JOURNAL%20OF%20AGING%20AND%20HEALTH&rft.pages=788-804&rft.spage=788&rft.stitle=J%20AGING%20HEALTH&rft.volume=29&rfr_id=info:sid/www.isinet.com:WoK:WOS&rft.au=Roberto%2C%20Pamela&rft.au=Tom%2C%20Sarah&rft.au=Gentry%2C%20Emma&rft.au=Stuart%2C%20Bruce&rft_id=info:doi/10%2E1177%2F0898264316645547

http://www.crossref.org.libproxy.unl.edu/openurl?pid=unl:unl1115&aulast=Dai&issn=08982643&volume=29&issue=5&spage=788&date=2017id=doi:info%3Adoi%2F10.1177%2F0898264316645547

**Comment by dallison1** [comment]
Wiley will be the same problem when it gets switched

**Comment by srickel1** [comment]
Looks to me like there is a problem with the resolution URL for Sage Journals in webbridge, if you are referring to the link that says
JOURNAL OF AGING AND HEALTH at Sage Journals

The last fields are  &date=#@YEAR#id=DOI:#@DOI#
Something about that doesn't look right to me

**Comment by dallison1** [comment]
Sage is fixed now.

**Comment by srickel1** [comment]
how was it fixed?  That would helpful to know for future .

**Comment by dallison1** [comment]
It was missing a “&” before the field name for DOI
