### ISSUE TITLE
replace graphic on site

### ISSUE THREAD

**Issue by dallison1** [unl-libraries/ezproxy#18]
please replace the unl graphic with the Nebraska graphic 
![nebraska](https://user-images.githubusercontent.com/17299921/37982699-ee7dd4e2-31b6-11e8-83fb-c76285a3be84.png)

**Comment by srickel1** [comment]
Our priority right now is to get things functional, and we will worry about redesign when we are ready to go production, as they might change the graphics and styles before then.  I'm going to set this as very low priority.

**Comment by mlitwa** [comment]
I just changed that logo on the login page, but I agree that these type of things are not really a priority right now

**Comment by dallison1** [comment]
Thanks – it is but you know how these things get in the way of functional testing.  I figured this was a quick fix.

DeeAnn Allison
Professor
402-472-3944
